
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import static java.awt.image.ImageObserver.WIDTH;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salih
 */
public class NewJFrame extends javax.swing.JFrame {
    private Customer currentCustomer = new Customer();
    private PaymentDialog paymentDialog = new PaymentDialog(this,true);
    private SaleDialog saleDialog = new SaleDialog(this,true);
    

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        ResultSet rs;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        this.setLocation((int)width/2-400 , (int)height/2-250);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pHome = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pCustomer = new javax.swing.JPanel();
        lblSurname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGsm = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPbx = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCustomerTrans = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pNewCustomer = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tfGetName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfGetSurname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfGetAddress = new javax.swing.JTextField();
        tfGetPbx = new javax.swing.JTextField();
        tfGetGsm = new javax.swing.JTextField();
        btSaveCustomer = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pSearchCustomer = new javax.swing.JPanel();
        tfGetSearchText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCustomers = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        pReport = new javax.swing.JPanel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        pMissingCustomer = new javax.swing.JPanel();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        pHome.setMaximumSize(new java.awt.Dimension(800, 500));
        pHome.setMinimumSize(new java.awt.Dimension(800, 500));
        pHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Müşteri Ara");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pHome.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 210, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Raporlar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pHome.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 210, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Borçlu Listele");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pHome.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 210, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Yeni Müşteri");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pHome.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 210, 40));

        getContentPane().add(pHome, "cardHome");

        pCustomer.setMaximumSize(new java.awt.Dimension(800, 500));
        pCustomer.setMinimumSize(new java.awt.Dimension(800, 500));
        pCustomer.setPreferredSize(new java.awt.Dimension(800, 500));

        lblSurname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSurname.setText("jLabel1");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblName.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Adres:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("GSM:");

        lblGsm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGsm.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ev Tel :");

        lblPbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPbx.setText("jLabel7");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("jLabel8");

        tbCustomerTrans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCustomerTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Tarih", "Satış Tutarı", "Ödeme Tutarı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCustomerTrans);
        tbCustomerTrans.getColumnModel().getColumn(0).setMinWidth(25);
        tbCustomerTrans.getColumnModel().getColumn(0).setPreferredWidth(25);
        tbCustomerTrans.getColumnModel().getColumn(0).setMaxWidth(25);
        tbCustomerTrans.getColumnModel().getColumn(1).setPreferredWidth(75);
        tbCustomerTrans.getColumnModel().getColumn(2).setResizable(false);
        tbCustomerTrans.getColumnModel().getColumn(3).setResizable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Son  İşlemler");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Ödeme");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Satış");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setText("Geri");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Kalan Borç    :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Kalan Borç:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("TL");

        javax.swing.GroupLayout pCustomerLayout = new javax.swing.GroupLayout(pCustomer);
        pCustomer.setLayout(pCustomerLayout);
        pCustomerLayout.setHorizontalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(20, 20, 20)
                        .addComponent(lblSurname))
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(lblAddress))
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(lblGsm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPbx))
                    .addComponent(jLabel9)
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pCustomerLayout.setVerticalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblSurname))
                .addGap(13, 13, 13)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblAddress))
                .addGap(3, 3, 3)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGsm)
                        .addComponent(jLabel6)
                        .addComponent(lblPbx)))
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(pCustomer, "cardCustomer");

        pNewCustomer.setMaximumSize(new java.awt.Dimension(800, 500));
        pNewCustomer.setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ad:");

        tfGetName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfGetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGetNameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Soyad:");

        tfGetSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Adres:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tel:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("GSM:");

        tfGetAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfGetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGetAddressActionPerformed(evt);
            }
        });

        tfGetPbx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfGetGsm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btSaveCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSaveCustomer.setText("Kaydet");
        btSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveCustomerActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Geri");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNewCustomerLayout = new javax.swing.GroupLayout(pNewCustomer);
        pNewCustomer.setLayout(pNewCustomerLayout);
        pNewCustomerLayout.setHorizontalGroup(
            pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewCustomerLayout.createSequentialGroup()
                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNewCustomerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSaveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pNewCustomerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pNewCustomerLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfGetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pNewCustomerLayout.createSequentialGroup()
                                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pNewCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(22, 22, 22)
                                        .addComponent(tfGetName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNewCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfGetPbx, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfGetSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfGetGsm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 538, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pNewCustomerLayout.setVerticalGroup(
            pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewCustomerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfGetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfGetSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfGetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(tfGetPbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGetGsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addGroup(pNewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSaveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pNewCustomer, "cardNewCustomer");
        pNewCustomer.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e)
            {
                tfGetName.requestFocusInWindow();
            }
        });

        pSearchCustomer.setMaximumSize(new java.awt.Dimension(800, 500));
        pSearchCustomer.setMinimumSize(new java.awt.Dimension(800, 500));
        pSearchCustomer.setPreferredSize(new java.awt.Dimension(800, 500));
        pSearchCustomer.setRequestFocusEnabled(true);

        tfGetSearchText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfGetSearchText.setToolTipText("Müşteri Adını Buraya Yazınız");
        tfGetSearchText.setPreferredSize(new java.awt.Dimension(100, 23));
        tfGetSearchText.setRequestFocusEnabled(true);
        tfGetSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGetSearchTextActionPerformed(evt);
            }
        });
        tfGetSearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfGetSearchTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGetSearchTextKeyTyped(evt);
            }
        });

        tbCustomers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Ad", "Soyad", "Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCustomers.setMinimumSize(new java.awt.Dimension(0, 0));
        tbCustomers.setRowHeight(20);
        tbCustomers.getTableHeader().setReorderingAllowed(false);
        tbCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCustomersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCustomers);
        tbCustomers.getColumnModel().getColumn(0).setMinWidth(25);
        tbCustomers.getColumnModel().getColumn(0).setPreferredWidth(25);
        tbCustomers.getColumnModel().getColumn(0).setMaxWidth(25);
        tbCustomers.getColumnModel().getColumn(1).setResizable(false);
        tbCustomers.getColumnModel().getColumn(2).setResizable(false);
        tbCustomers.getColumnModel().getColumn(3).setResizable(false);
        tbCustomers.setSelectionMode (ListSelectionModel.SINGLE_SELECTION);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Geri");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSearchCustomerLayout = new javax.swing.GroupLayout(pSearchCustomer);
        pSearchCustomer.setLayout(pSearchCustomerLayout);
        pSearchCustomerLayout.setHorizontalGroup(
            pSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchCustomerLayout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(pSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(tfGetSearchText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(pSearchCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSearchCustomerLayout.setVerticalGroup(
            pSearchCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchCustomerLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(tfGetSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pSearchCustomer, "cardSearchCustomer");
        pSearchCustomer.requestFocus();
        pSearchCustomer.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e)
            {
                tfGetSearchText.requestFocusInWindow();
            }
        });

        pReport.setFocusCycleRoot(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Toplam Satış :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Gelen Nakit :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Toplam Satış :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Gelen Nakit :");

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Geri");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pReportLayout = new javax.swing.GroupLayout(pReport);
        pReport.setLayout(pReportLayout);
        pReportLayout.setHorizontalGroup(
            pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReportLayout.createSequentialGroup()
                .addGroup(pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pReportLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228)
                        .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pReportLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(pReportLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(pReportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147))
        );
        pReportLayout.setVerticalGroup(
            pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReportLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addGroup(pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pReport, "cardReport");

        pMissingCustomer.setMaximumSize(new java.awt.Dimension(800, 500));
        pMissingCustomer.setMinimumSize(new java.awt.Dimension(800, 500));
        pMissingCustomer.setPreferredSize(new java.awt.Dimension(800, 500));

        dateChooserCombo3.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("Geri");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMissingCustomerLayout = new javax.swing.GroupLayout(pMissingCustomer);
        pMissingCustomer.setLayout(pMissingCustomerLayout);
        pMissingCustomerLayout.setHorizontalGroup(
            pMissingCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMissingCustomerLayout.createSequentialGroup()
                .addGroup(pMissingCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMissingCustomerLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMissingCustomerLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(dateChooserCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMissingCustomerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(588, Short.MAX_VALUE))
        );
        pMissingCustomerLayout.setVerticalGroup(
            pMissingCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMissingCustomerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dateChooserCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pMissingCustomer, "cardMissing");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardSearchCustomer");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardNewCustomer");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardReport");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardMissing");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tfGetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGetNameActionPerformed

    private void tfGetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGetAddressActionPerformed

    private void tfGetSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGetSearchTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfGetSearchTextActionPerformed

    private void tbCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCustomersMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            System.out.println(tbCustomers.getSelectedRow());
            int id = (int) tbCustomers.getValueAt(tbCustomers.getSelectedRow(), 0);
            try {
                currentCustomer = DatabaseOperations.getCustomer(id);
                showCustomerCard(currentCustomer);

            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }            
            }

        
    }//GEN-LAST:event_tbCustomersMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardHome");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardHome");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardHome");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)getContentPane().getLayout();
        cl.show(getContentPane(), "cardHome");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveCustomerActionPerformed
        // TODO add your handling code here:
        if(!tfGetName.getText().isEmpty() && !tfGetSurname.getText().isEmpty()){
            try {
                currentCustomer = new Customer();
                currentCustomer.setCustomertoDatabase(tfGetName.getText(), tfGetSurname.getText(), tfGetAddress.getText(), tfGetPbx.getText(), tfGetGsm.getText(), null, null);

                currentCustomer = DatabaseOperations.saveCustomer(currentCustomer);
                JOptionPane.showMessageDialog(this, "Müşteri Kaydedildi.");
                showCustomerCard(currentCustomer);
                



                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        else{
        }
    }//GEN-LAST:event_btSaveCustomerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        paymentDialog.setCustomer(currentCustomer);
        paymentDialog.setLocationRelativeTo(this);
        paymentDialog.setVisible(true);
        
        showCustomerCard(currentCustomer);

        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        saleDialog.setCustomer(currentCustomer);
        saleDialog.setLocationRelativeTo(this);
        saleDialog.setVisible(true);
        
        showCustomerCard(currentCustomer);

        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void tfGetSearchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGetSearchTextKeyTyped

       
    }//GEN-LAST:event_tfGetSearchTextKeyTyped

    private void tfGetSearchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGetSearchTextKeyReleased
        // TODO add your handling code here:
        
        
            DefaultTableModel model = (DefaultTableModel)tbCustomers.getModel();
            model.getDataVector().removeAllElements();
            tbCustomers.addNotify();
        try {
            ResultSet matchedCustomers = DatabaseOperations.searchCustomers(tfGetSearchText.getText());
             
            
            while(matchedCustomers.next()){
                Object[] rowData = new Object[4];
                rowData[0] = matchedCustomers.getInt(1);
                rowData[1] = matchedCustomers.getString(2);
                rowData[2] = matchedCustomers.getString(3);
                rowData[3] = matchedCustomers.getString(4);
                model.addRow(rowData);

            }
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tfGetSearchTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        DatabaseOperations.initializeDB();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSaveCustomer;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblGsm;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPbx;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JPanel pCustomer;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pMissingCustomer;
    private javax.swing.JPanel pNewCustomer;
    private javax.swing.JPanel pReport;
    private javax.swing.JPanel pSearchCustomer;
    private javax.swing.JTable tbCustomerTrans;
    private javax.swing.JTable tbCustomers;
    private javax.swing.JTextField tfGetAddress;
    private javax.swing.JTextField tfGetGsm;
    private javax.swing.JTextField tfGetName;
    private javax.swing.JTextField tfGetPbx;
    private javax.swing.JTextField tfGetSearchText;
    private javax.swing.JTextField tfGetSurname;
    // End of variables declaration//GEN-END:variables

protected MaskFormatter createFormatter(String s) {
    MaskFormatter formatter = null;
    try {
        formatter = new MaskFormatter(s);
    } catch (java.text.ParseException exc) {
        System.err.println("formatter is bad: " + exc.getMessage());
        System.exit(-1);
    }
    return formatter;
}

private  void showCustomerCard(Customer customer){

    lblName.setText(customer.name);
    lblSurname.setText(customer.lastName);
    lblAddress.setText(customer.address);
    lblPbx.setText(customer.pbx);
    lblGsm.setText(customer.gsm);
    
    

        try {
            ResultSet transactions = DatabaseOperations.getTransactions(customer);
            
            // transaction = t_id, paymentAmount, saleAMount, transDate
        
            DefaultTableModel model = (DefaultTableModel)tbCustomerTrans.getModel();
            model.getDataVector().removeAllElements();
            tbCustomerTrans.addNotify();
       
            
             
            
            while(transactions.next()){
                System.out.println("SuP");
                Object[] rowData = new Object[4];
                rowData[0] = transactions.getInt(1); // t_id
                rowData[3] = transactions.getString(2); // t_paymentAmount
                rowData[2] = transactions.getString(3); // t_sale
                rowData[1] = transactions.getDate(4); // t_date
                model.addRow(rowData);

            }
            
            // Setting up the transactions table
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            CardLayout cl = (CardLayout)getContentPane().getLayout();
    cl.show(getContentPane(), "cardCustomer");
        
    
}
 
}
